export const KeyRange = [
  { key: "mid2E以下", id: 0 },
  { key: "mid2F", id: 1 },
  { key: "mid2F#", id: 2 },
  { key: "mid2G", id: 3 },
  { key: "mid2G#", id: 4 },
  { key: "hiA", id: 5 },
  { key: "hiA#", id: 6 },
  { key: "hiB", id: 7 },
  { key: "hiC", id: 8 },
  { key: "hiC#", id: 9 },
  { key: "hiD", id: 10 },
  { key: "hiD#", id: 11 },
  { key: "hiE", id: 12 },
  { key: "hiF", id: 13 },
  { key: "hiF#", id: 14 },
  { key: "hiG", id: 15 },
  { key: "hiG#", id: 17 },
  { key: "hihiA", id: 18 },
  { key: "hihiA#", id: 19 },
  { key: "hihiB", id: 20 },
  { key: "hihiC", id: 21 },
  { key: "hihiC#", id: 22 },
  { key: "hihiD", id: 23 },
  { key: "hihiD#", id: 24 },
  { key: "hihiE", id: 25 },
  { key: "hihiF以上", id: 26 },
];
